version: 2

sources:
  - name: master
    database: postgres
    schema: src
    tables:
      - name: customers
        description: '顧客データ'
      - name: products
        description: '商品データ'
  - name: transaction
    database: postgres
    schema: src
    tables:
      - name: orders
        description: '注文データ'
      - name: order_details
        description: '注文詳細データ'
